GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphcmVkLmh1dGNoaW5zb245OUBnbWFpbC5jb20iLCJpYXQiOjE1MTI1MzQ3NDgsImV4cCI6MTUxMzEzOTU0OCwic3ViIjoiNWEyNzUxNjBmYTRmNzRlZDkyYTllZTk4In0.iQbRF1piBfaBA00pPkJd7tdDKMdnglg4tz8iLlkBFGQ

### Register

POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "jared.hutchinson99@gmail.com",
  "firstName": "Jared",
  "lastName": "Hutch",
  "password": "password123"
}

### Sign in
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "jared.hutchinson99@gmail.com",
  "password": "password123"
}